### ISSUE TITLE
kcl.yaml Is the option parameter of kcl now deprecated?

### ISSUE THREAD

**Issue by riven-blade** [KusionStack/kusion#1002]
### What would you like to be added?

kcl.yaml Is the option parameter of kcl now deprecated?

### Why is this needed?

kcl.yaml Is the option parameter of kcl now deprecated?

**Comment by liu-hm19** [comment]
@riven-blade Hello, for the purpose of simplifying the `Stack` directory structure, we have deprecated the `kcl.yaml` file. However, the related functionalities can still be achieved through the `kcl.mod` file and command line flags. 
- You can declare the KCL files that need to be jointly compiled in the `entries` field of `kcl.mod` file, more information can be found at [here](https://github.com/kcl-lang/kpm/blob/main/docs/kcl_mod.md#entries). 
- You can pass in the parameters that need to specified when generating the `Spec` via the `-D` flag of `kusion generate`, `kusion preview` and `kusion apply`, which will be updated in the version of **v0.12.0**.
