### ISSUE TITLE
GLCC Project: Large Language Model (LLM) Operations Based on Kusion / 基于 Kusion 的大语言模型（LLM）运维

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#1134]
# Background

Based on the current workflow of Kusion and the mechanism of [Kusion Module](https://www.kusionstack.io/docs/concepts/kusion-module/overview), build an operation workflow for LLM that implements the automated deployment of LLM.

# Objective

Construct an LLM operation workflow based on Kusion.

# Output Requirements

Specifically, the tasks include:

1. Develop a Schema definition for application development based on a mainstream LLM.
2. Create a standardized platform configuration definition for platform engineers based on a mainstream LLM.
3. Complete the automated deployment of a mainstream LLM using the current Kusion workflow.
4. Implement a test AI Agent application to call the deployed LLM.

# Skills Requirements

1. Familiar with Go language.
3. Basic knowledge of LLM.
3. Understanding of Kubernetes.

# 背景
基于 Kusion 当前的工作流和 [Kusion Module](https://www.kusionstack.io/docs/concepts/kusion-module/overview) 的机制，构建针对 LLM 的运维流程，实现 LLM 的自动化部署

# 目标
构建基于 Kusion 的 LLM 运维工作流

# 产出要求
具体包含如下任务：
1. 基于某个主流的 LLM 构建面向应用研发的 Schema 定义
2. 基于某个主流的 LLM 构建面向平台工程师的平台标准化配置定义
3. 基于当前 Kusion 工作流，完成对某个主流 LLM 的自动化部署
4. 实现一个测试 AI Agent 应用完成对部署 LLM 的调用

# 能力要求
1. 熟悉 Go 语言
2. 了解 LLM 的基础知识
3. 了解 Kubernetes

**Comment by n3A87** [comment]
请问这个项目现在有意向人选了吗~

**Comment by liu-hm19** [comment]
@n3A87 同学你好～目前这个项目还在招募中，欢迎了解和报名。同学可以在 Kusion 项目的 [官方网站](https://www.kusionstack.io/docs/) 获取更多关于 Kusion 的介绍，也可以邮件联系项目导师进行沟通，如果方便的话，同学可以提交一份个人简历以及针对这个项目的 Proposal (形式不限，Word/PDF/Markdown 文件均可) 至导师邮箱，这样我们可以更加了解同学的背景和想法。感谢同学的关注，预祝开源夏令营顺利！

**Comment by liu-hm19** [comment]
Fixed by https://github.com/KusionStack/kusion/issues/1307
