### ISSUE TITLE
Enhancement: Optimize KusionStack Install Process

### ISSUE THREAD

**Issue by chai2010** [KusionStack/kusion#117]

**Comment by SparkYuan** [comment]
another requirement #21

**Comment by SparkYuan** [comment]
Current CDN is unstable and slow, should we provide a open OSS for public users to download kusion

**Comment by Peefy** [comment]
KCLVM Releted Issue: https://github.com/KusionStack/KCLVM/issues/53

**Comment by ldxdl** [comment]
Could users install kusion via go get? Could kusionup install kusion via go get?

**Comment by howieyuen** [comment]
> Could users install kusion via go get? Could kusionup install kusion via go get?

yeah, go install absolutely can do it, but kusion installing not only install kusion, but also kclvm, kcl tools, and configure kusion path, etc.
so, kusionup is burn, it installs kusionCLI, kclvm, kcl tools ...

**Comment by ldxdl** [comment]
> > Could users install kusion via go get? Could kusionup install kusion via go get?
> 
> yeah, go install absolutely can do it, but kusion installing not only install kusion, but also kclvm, kcl tools, and configure kusion path, etc. so, kusionup is burn, it handles all stuff...

What I prefer or I think reasonable is:
1. Kusion via `go get`, brew or any other way, by which users could install it with a line command. Kclvm, the most important component with Kusion, should be auto-installed with kusion, by an install script? Or just embeded in it?
2. Kusion's components/tools should be installed and managed by Kusion itself via a kusion subcommand, like `kusion install foo`? Users just install what they indeed.
3. KCL's components/tools should be installed and managed by KCL itself via a kcl subcommand, like `kcl install bar`? Users just install what they indeed.
4. Konfig repo could be installed by `kusion install konfig` or auto-installed with other command like init, or just auto-install Konfig with Kusion at the first place. The Konfig install path is a tricky problem to consider.
5. For users who just want use run some projects(no code, no dev), we should provide a command like `kusion run proj-foo` to download & unzip & preview & apply & watch it.
6. While users should be build & publish a project to a project registry.

**Comment by howieyuen** [comment]
Totally agree. Use subcommand or plugin to simplify install process. Now kusion tarball contains:
1. kusion binary
2. kclvm
3. kcl-openapi
4. kcl-go

**Comment by howieyuen** [comment]
I make a proposal, see here : https://github.com/KusionStack/kusion/issues/178

**Comment by SparkYuan** [comment]
https://github.com/KusionStack/kusionstack.io/pull/208
