### ISSUE TITLE
Feat: Support Path-Style of bucket for s3 Storage backend

### ISSUE THREAD

**Issue by hoangndst** [KusionStack/kusion#1178]
### What would you like to be added?

The Path-Style bucket link for the S3 storage option.

### Why is this needed?

Currently, the endpoint of S3 is only in Virtual-hosted–style: https://bucket_name.s3.example.com/. The error will occur if in the case of S3 Storage Server only supports Certificate for Path-Style like https://s3.example.com/bucket_name/
```sh
✘  get workspaces meta data from s3 failed: RequestError: send request failed
      caused by: Get "https://bucket_name.s3.example.com/.metadata.yml": tls: failed to verify certificate: x509: certificate is valid for *.example.com, example.com, not bucket_name.s3.example.com`
```

**Comment by liu-hm19** [comment]
Thank you very much for raising this issue. We will follow up on this ASAP and try to provide an release-candidate version supporting the `path-style` bucket for S3 storage backend for you by next Wednesday. If you have the time and interest, you are also warmly welcome to submit a pull request yourself : ) It will be great to have you as a committer for Kusion!
