### ISSUE TITLE
Feat: Enable skip delete import tf resource when destroy

### ISSUE THREAD

**Issue by hoangndst** [KusionStack/kusion#1200]
### What would you like to be added?

Option skip delete imported tf resource when destroying release.

### Why is this needed?

When the imported tf resource is still used by another release, we need to retain it so that the release using that resource can function properly.

**Comment by SparkYuan** [comment]
@hoangndst  Thank you for your feedback! This is indeed a valuable suggestion! Are you interested in implementing this feature?

**Comment by hoangndst** [comment]
About this feature. I plan to add an `IgnoreExternal` field to the model [Operator](https://github.com/KusionStack/kusion/blob/main/pkg/engine/operation/models/operation_context.go#L15) so from there the user can pass the command e.g. `kusion destroy --ignore-external` to the lower part to handle. 
cc @SparkYuan looking for your view of this!

**Comment by hoangndst** [comment]
That much better
