### ISSUE TITLE
Feat: add a new command kusion release show

### ISSUE THREAD

**Issue by liu-hm19** [KusionStack/kusion#1262]

**Comment by liu-hm19** [comment]
This issue is used to track the development of `kusion release show` command. After discussing with @hoangndst, we believe that we can achieve the display of application resources by adding `--project` and `--resource-id` to the originally planned `kusion release show` command to implement the functionality mentioned in [this issue](https://github.com/KusionStack/kusion/issues/1261). And the implementation of `kusion release show` is also assigned to @hoangndst. 

BTW, due to the limitations of GitHub, you may need to first comment on this issue so that I can assign it to you. 😂 

Thanks a lot for your contributions! Looking forward to the related PR. We will review it ASAP : ) 

cc @ffforest @ekjotsinghmakhija

**Comment by hoangndst** [comment]
Oke 😁
