### ISSUE TITLE
Finish GLCC Project: Large Language Model (LLM) Operations Based on Kusion

### ISSUE THREAD

**Issue by kaysonyu** [KusionStack/kusion#1307]
I have completed the tasks outlined in issue #1134 for GLCC Project and have submitted several PRs to address the issue. Below are the links to each PR and a brief description of what they accomplish:

https://github.com/KusionStack/catalog/pull/91 
feat: finish schema of module inference

https://github.com/KusionStack/catalog/pull/92
fix: correct inference module pod spec generate

https://github.com/KusionStack/catalog/pull/93
fix(inference): enable generated YAML matches the correct resources

https://github.com/KusionStack/catalog/pull/94
fix(inference): fix portName and env name; finish the example

https://github.com/KusionStack/catalog/pull/96
refactor(inference): change the structure of the inference module

https://github.com/KusionStack/catalog/pull/99
feat(inference): add a proxy to easily switch models

https://github.com/KusionStack/kusionstack.io/pull/573
chore: add a introduction of changing the model in inference module

**Comment by liu-hm19** [comment]
Thanks a lot for your hard work! And welcome to continue participating in KusionStack community and contributing your exciting ideas and codes to the project : )
