### ISSUE TITLE
Research: Backstage x Kusion Server

### ISSUE THREAD

**Issue by ffforest** [KusionStack/kusion#1322]
### What would you like to be added?

Build Kusion portal with Backstage

### Why is this needed?

Figure out the possibility to build the kusion portal using Backstage

**Comment by Yangyang96** [comment]
After thorough discussions with @hoangndst, we have decisively established our plan to build 3 Backstage plugins for the integration of Kusion with `Backstage`:

1. **Backstage Catalog Entity Provider**: This plugin will effectively convert Kusion entities into Backstage entities.
2. **Scaffolder Backend Module**: This module will deliver templates for Kusion operations as creating actions.
3. **Kusion Plugin**: This plugin will showcase crucial `run` related information, enhancing your experience in Backstage.

The `Kusion plugin` will launch after Kusion 1.0, while the first two plugins will be available in the [kusion-backstage-plugin](https://github.com/KusionStack/kusion-backstage-plugin) repository alongside Kusion 1.0.

We will also provide utility SDKs to empower our community to create Backstage plugins for Kusion in the future.
