### ISSUE TITLE
Feat: Add Kusion Resource URN and improve Kusion Resource ID validation

### ISSUE THREAD

**Issue by ffforest** [KusionStack/kusion#1355]
### What would you like to be added?

Add Kusion Resource URN which includes project, stack and workspace information to make it a globally unique identifier.
Kusion Resource ID only needs to be unique inside a Spec.

### Why is this needed?

Kusion Resource ID is input to Kusion Engine, whereas Kusion Resource URN is for Kusion resource manager.
They should be distinct concepts.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added KusionResourceURN field to the Resource struct in pkg/domain/entity/resource.go. This new field will store the globally unique identifier that includes project, stack, and workspace information. The existing KusionResourceID field is kept as a locally unique identifier within a Spec.

You can review changes in this commit: https://github.com/jacks-sam1010/KusionStack-kusion-1355/commit/32d8b787629cc315d3a766b12528c85d70a9d74d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
