### ISSUE TITLE
Bug: DependsOn in state does not update accordingly if resource is unchanged

### ISSUE THREAD

**Issue by ffforest** [KusionStack/kusion#1358]
### What happened?

Pre-requisite for this bug:
- resource A depends on resource B
- resource B name changed -> i.e. resource B ID changed
- resource A stays unchanged in the last apply

State before apply:
```
xxx:xxx:xxx:ResourceBOld:
  ...
xxx:xxx:xxx:ResourceA:
  ...
  DependsOn:
  - xxx:xxx:xxx:ResourceBOld
```

State after a successful apply:
```
xxx:xxx:xxx:**ResourceBNew**:
  ...
xxx:xxx:xxx:ResourceA:
  ...
  DependsOn:
  - xxx:xxx:xxx:**ResourceBOld**
```

This will cause an issue in the next apply:
`can't find resource by key:xxx:xxx:xxx:ResourceBOld in models or state`

### What did you expect to happen?

After a successful apply:
State:
```
xxx:xxx:xxx:ResourceBNew:
  ...
xxx:xxx:xxx:ResourceA:
  ...
  DependsOn:
  - xxx:xxx:xxx:ResourceB**New**
```

### How can we reproduce it (as minimally and precisely as possible)?

All of the following conditions are met:
1. resource A depends on resource B
2. resource B name changed -> i.e. resource B ID changed
3. resource A stays unchanged in the last apply

### Anything else we need to know?

In case of an unchanged resource, `res` is set to `prior`, aka. the resource in the last release state:
https://github.com/KusionStack/kusion/blob/main/pkg/engine/operation/graph/resource_node.go#L349

`res` gets updated as part of `RefreshResourceIndex`:
https://github.com/KusionStack/kusion/blob/main/pkg/engine/operation/graph/resource_node.go#L360

and later gets updated into the new release:
https://github.com/KusionStack/kusion/blob/main/pkg/engine/operation/graph/resource_node.go#L363

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by riven-blade** [comment]
Yes, I verified that this problem does exist. I added a line of code here and it should be able to be fixed.
<img width="630" alt="image" src="https://github.com/user-attachments/assets/1cf57050-2cb7-46f2-a3fd-e7e3c3ab097a" />

```go
	case models.UnChanged:
		log.Infof("planed resource and live resource are equal")
		// auto import resources exist in intent and live cluster but not recorded in release file
		if prior == nil {
			response := rt.Import(context.Background(), &runtime.ImportRequest{
				PlanResource: planed,
				Stack:        operation.Stack,
			})
			s = response.Status
			log.Debugf("import resource:%s, resource:%v", planed.ID, json.Marshal2String(s))
			res = response.Resource
		} else {
			prior.DependsOn = planed.DependsOn
			res = prior
		}
```

**Comment by riven-blade** [comment]
For resources that have not changed, just update the recalculated dependencies.
```go
prior.DependsOn = planed.DependsOn
```
