### ISSUE TITLE
support kusion release in features of dev containers in github.dev

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#163]
### background: about github.dev and dev containers

github.dev is a web-based editor and its business version support running dev containers within the online workspace.

The codespace can start a container that is defined and configured by a custom `devcontainers.json` file within the code repo.
The `devcontainers.json` file usually consists of configurations such as a base image, some add-on features, and some commands that will be run after the container creates/starts.

### what do we need to support

We need to contribute **a kusion feature** to the dev container features. And **the kusion feature** needs to support kusion and KCL usage within the container:
- make kusion(including all the toolkits) available to use out-of-box
- by default install the kusionIDE and KCLIDE extensions into the codespace

The available dev container features are listed [here](https://containers.dev/features). For example, there is [Kubernetes-Minikube-in-docker](https://github.com/devcontainers/templates/tree/main/src/kubernetes-helm-minikube) feature. And kusion can be an add-on feature to collaborate with that to provide a local quick-start experience. Also, kusion can be adopted independently to provide experience to the remote cloud.

### some helpful materials

- [dev container feature quick start](https://github.com/devcontainers/feature-starter)
- [here's the cue's feature of dev containers](https://github.com/rchaganti/vsc-devcontainer-features)
- [guide about creating custom devContainer features](https://containers.dev/guide/author-a-feature)

**Comment by amyXia1994** [comment]
There are two kinds of dev Container features that kusion can contribute:
1. the kusion-quick-start experience provider: with all the kusion toolkits and minikube environment.
2. the classic konfig development experience provider: kusion environment with all the kusion toolkits.

**Comment by amyXia1994** [comment]
VS Code supports devContainers, too! It's a good substitute for users who does not have a github.dev business account.

https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-try-a-development-container

**Comment by amyXia1994** [comment]
- badge: https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-codespaces-badge
- prebuild: https://docs.github.com/en/codespaces/prebuilding-your-codespaces
- automatically open files when launching the workspace: https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/automatically-opening-files-in-the-codespaces-for-a-repository

**Comment by amyXia1994** [comment]
Almost done:

- [X] Merged: a kusion feature is created in the devcontainer-features repo: https://github.com/KusionStack/devcontainer-features/pkgs/container/devcontainer-features%2Fkusion
- [X] Merged: the devcontainer.json file is created and tested work in the konfig repo: https://github.com/KusionStack/konfig/pull/64
- [ ] PR created, waiting for owners to review: add the kusion features to the devcontainer feature collection index: https://github.com/devcontainers/devcontainers.github.io/pull/91, once merged, these two index lists will be updated: [features index](https://containers.dev/features) and [collection list](https://containers.dev/collections)

**Comment by amyXia1994** [comment]
quick start go-city example:
- port forward 4000: the go-city program will first fetch go projects from git through network and CORS will occur and the fetching will be failed.

refs:
- https://docs.github.com/en/codespaces/developing-in-codespaces/forwarding-ports-in-your-codespace
- https://github.com/community/community/discussions/15351
- https://notes.alexkehayias.com/codespaces-doesn-t-allow-requests-across-ports-from-a-preview/

**Comment by SparkYuan** [comment]
@amyXia1994 All tasks listed in this issue are completed. Can we close this issue now?

**Comment by amyXia1994** [comment]
> @amyXia1994 All tasks listed in this issue are completed. Can we close this issue now?

Yeah, I'll close it now.
