### ISSUE TITLE
LiveDiff is updated, but Action is Create

### ISSUE THREAD

**Issue by howieyuen** [KusionStack/kusion#169]
Calculate **APPLY** actions:
`1` means not nil, `0` means nil
prior | plan | live | action | remark
--|--|--|--|--
1 | 1 | 1 | update |
1 | 1 | 0 | update | use `kusion apply` first, then resources are deleted without kusion.
1 | 0 | 1 | delete |
1 | 0 | 0 | delete | resources are create or updated with kusion, then deleted beforehand without kusion, now perform `kusion destory`
0 | 1 | 1 | update |
0 | 1 | 0 | create |
0 | 0 | 1 | delete | resources are created beforehand without kusion, now perform `kusion destory`
0 | 0 | 0 | --- | never reach

**Comment by SparkYuan** [comment]
Ref: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merging-changes-to-primitive-fields

**Comment by howieyuen** [comment]
> Ref: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merging-changes-to-primitive-fields

the ref link calculates patch body, operate on resource's fields, preview cmd calculates resource action, operates on resource itself. Cannot take as same.
