### ISSUE TITLE
Feat: Add watch & healthcheck for K8s networking.k8s.io/v1

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#173]
## Enhancement

We currently have supported watching and health-checking for some k8s native resources when we use command `kusion apply --watch`. It is a very useful feature for users to understand what is happening and whether resources are ready to use when they are operating k8s resources.

More k8s native resources are required to be supported by Kusion. This issue is used to track resources in `networking.k8s.io/v1`

- [ ] IngressClass
- [x] Ingress
- [ ] NetworkPolicy

More details can be found in #23

**Comment by jakezhu9** [comment]
Hi, I'm interested in this issue and I'd like to work on it. Could you please assign this to me?

**Comment by howieyuen** [comment]
> Hi, I'm interested in this issue and I'd like to work on it. Could you please assign this to me?

Yeah, of course. welcome to  KusionStack community 😄

**Comment by jakezhu9** [comment]
I've implemented networking.k8s.io/v1.Ingress (#308).

However, for IngressClass and NetworkPolicy, I searched through konfig and couldn't find any related codes or examples. It looks like kusion doesn't support them yet.

So, I'm planning on taking some extra time to implement these features before moving on to watch and healthcheck. It might take a bit longer.

If you have any other suggestions or ideas, please don't hesitate to let me know!

**Comment by Peefy** [comment]
> > I've implemented networking.k8s.io/v1.Ingress (#308).
> > However, for IngressClass and NetworkPolicy, I searched through konfig and couldn't find any related codes or examples. It looks like kusion doesn't support them yet.
> > So, I'm planning on taking some extra time to implement these features before moving on to watch and healthcheck. It might take a bit longer.
> > If you have any other suggestions or ideas, please don't hesitate to let me know!
> 
> Yes, indeed, we haven't added `IngressRule` and `IngressClass` to konfig, we need to transform these definitions to kcl schema.
> 
> And we have a simple tool, named [kcl-openapi](https://github.com/KusionStack/kcl-openapi). Honestly speaking, it's not a delightful CLI tool, but might offer some help to you.
> 
> Feel free to contact us, Email, Slack, DingTalk, WeChat, choose your favorite 😄

Ping @amyXia1994. @jakezhu9 wants to figure out which files they are generated from. Could you please give him some guidance on it?

**Comment by SparkYuan** [comment]
tracked in https://github.com/KusionStack/kusion/issues/23
