### ISSUE TITLE
Invalid triple: "windows" ([Darwin ubuntu centos Darwin-arm64])

### ISSUE THREAD

**Issue by 1511563371** [KusionStack/kusion#179]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`1 ENV `
> OS: win10
> GoVersion : 1.19.1

`2 process`
```
step1:  download the source code kusioin-0.7.1
step2 : cd  ./Makefile && vi Makefile
step3:  follow the context [ build-local-windows-all: build-local-windows  ## Build kusion & kcl tool chain for windows]
step4 : use PS C:\XXX\XXX\Desktop\kusion\kusion-0.7.1> go run ./scripts/install-kclvm --triple=windows --outdir=./_build/bundles/kusion-windows/kclvm
```
`3 result`
```
Invalid triple: "windows" ([Darwin ubuntu centos Darwin-arm64])
exit status 1
```

**Comment by amyXia1994** [comment]
Hello @1511563371 welcome to KusionStack, for now, you can try kusion with GitHub codespaces(the webIDE by Github), for example, you can create it within the konfig [repo](https://github.com/KusionStack/konfig) and click the [Open in GitHub CodeSpaces] badge to begin your trial. Hope that will solve your problem for the moment.

![image](https://user-images.githubusercontent.com/29722609/205578724-64d92153-9ffb-4090-b982-c095eddfef09.png)
