### ISSUE TITLE
Enhancement: More user perspective hint when the cluster is not running

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#191]
## Enhancement

In following scenarios, with:
- no minikube installed, or
- minikube newly installed and not started ever after, or
- minikube stopped

`kusion preview` and `kusion apply` command produces error like: 
` ❌  stat /Users/amy/.kube/config: no such file or directory`, or 
`❌  invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`.

That's kind of confusing for users and in users' perspective, could be better to provide a supplementary hint to **guide users, like, to check if their cluster is running or to start their local minikube, etc**

**Comment by howieyuen** [comment]
this is reasonable and acceptable, similar like https://github.com/KusionStack/kusion/issues/188
assign @markliby

**Comment by SparkYuan** [comment]
@liu-hm19 You can fix Konfig CI Kubernetes runtime error and issue together

**Comment by SparkYuan** [comment]
fixed in https://github.com/KusionStack/kusion/pull/409
