### ISSUE TITLE
[Bug] Failed to install kusion using the go install command in readme.

### ISSUE THREAD

**Issue by Peefy** [KusionStack/kusion#233]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run the following command:

```bash
go install github.com/KusionStack/kusion@main && echo a=1 > a.k && kusion compile a.k
```

### 2. What did you expect to see? (Required)

Installation succeeded and the YAML output:

```yaml
a: 1
```

### 3. What did you see instead (Required)

I see the following message:

```
go: github.com/KusionStack/kusion@main: github.com/KusionStack/kusion@v0.7.3-0.20230202092922-ee0d8cac0e2a: parsing go.mod:
	module declares its path as: kusionstack.io/kusion
	        but was required as: github.com/KusionStack/kusio
```

Perhaps the following install command is correct:

```
go install kusionstack.io/kusion@main
```

BTW, when I use the above command to install successfully, next I encountered the following error:

```bash
$ echo a=1 > a.k && kusion compile a.k
 ❌  path must be a stack directory
```

### 4. What is your KusionStack components version? (Required)

The main branch [ee0d8ca](https://github.com/KusionStack/kusion/commit/ee0d8cac0e2a4ab77a5f1b5c9c44ce28c66d0a1d)

**Comment by howieyuen** [comment]
Thanks for this report. 
The go install address should be `kusionstack.io/kusion@latest`, I forget update the README doc.
And  the version should be latest tag, not main branch.

The compile issue, the logic is changed by #230, please @SparkYuan fix it

**Comment by healthjyk** [comment]
test comment
