### ISSUE TITLE
Feature: Provide unified, stable domain layer serving for both cmd and Kusion service layer

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#248]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Kusion supports both cmd and service layer, while service layer exposes more abilities than cmd. However, Kusion is designed for the usage of cmd from the beginning, so the service layer have to use some "KUSION INTERNAL" functions to realize these additional abilities. Although these functions are golang external functions, but actually "KUSION INTERNAL" functions —— changing frequently, not having stable stable input&output format and exposing consistent ability, which brings a lot of trouble to the service layer.  
Besides, functions which are golang external can be used by anyone else, requiring the stability of these functions; unless the major version is upgraded showing incompatible changes.

**Describe the feature you'd like:**
Kusion provide unified and stable domain layer, including the definition of object and function. _**Above the domain layer, there are the cmd and service layer.**_
Besides, more standard version management should be applied, incompatible changes should only happen when the major version changing. SHOULD be very careful to the alteration of domain layer.

**Teachability, Documentation, Adoption, Migration Strategy:**
The framework of DDD could be applied, ref: https://en.wikipedia.org/wiki/Domain-driven_design

**Comment by LeoLiuYan** [comment]
Glad to see this proposal !
