### ISSUE TITLE
Reduce the initialization of runtime when using preview&apply

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#250]
## Enhancement
When calling preview or apply, runtime is initialized. However, the initialization will be done every preview/apply call, causing the waste of the I/O and compute. Consider setting the initialed runtimes as an input in domain layer.

**Comment by howieyuen** [comment]
For CLI, initialized runtime once should be guaranteed during one ops, for server, should not be initialized again util reboot.

**Comment by SparkYuan** [comment]
Duplicated https://github.com/KusionStack/kusion/issues/188
