### ISSUE TITLE
[Feature Request] Kusion provides API for integration tools

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#265]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now the extension is accomplishing its goals by executing the kusion binary for each time and then resolve the `stdout & stderr`, but since the stdout/stderr of kusion binary are not designed for tools integration, the output messages like this are disturbing:
![image](https://user-images.githubusercontent.com/29722609/222616140-f73aaf16-c055-4a4c-9799-80452a46ff83.png)

the vscode-kusion extension requires kusion to provide APIs for tools to integrate kusion's capacities more elegantly and normatively. 

**Describe the feature you'd like:**

At least a few Go APIs of kusion are required:
- compile
- preview
- apply
- watch
- list projects
- list stacks
- list templates

### ListTemplates API

- API id：`init.ListTemplates`
- params:

| name | type | required | default value | description | example |
| ----- | ----- | -------- | ------------- | ----------- | --------- |
| online | boolean | optional | false | determines if kusion downloads templates from online repo | `true`, `false` |
| url | string | optional | `"https://github.com/KusionStack/kusion-templates"` | the online repo url, meaningful only when `online==true`|  |
| fsPath | string | optional |  | the fsPath to find the templates, meaningful only when `online == false` |`/path/to/templates` |

- returns:

| name | type | description | example |
| ----- | ----- | ----------- | -------- |
| templateList | Template[] | list of templates found | |
| err | Error | error code and message | `{"code":"invalidPath"， "message":"path not exists (or repo url not exists)"}` |

```go
type Template struct {
    name string
    description string
    content string // now the template could be the content of `kusion.yaml` file under the template directory: for example https://github.com/KusionStack/kusion-templates/blob/main/code-city/kusion.yaml
}

type Error struct {
    code  string
    message string
}
```

**Comment by howieyuen** [comment]
cc @healthjyk

**Comment by amyXia1994** [comment]
### LiveDiffPreview API

API id：status.LiveDiffPreview
params:

| name | type | required | default value | description | example |
| ----- | ----- | -------- | ------------- | ----------- | --------- |
| stack | string | required |  | path to the target stack to show live diff preview information  | `appops/guestbook/dev` |

- returns:

| name | type | description | example |
| ----- | ----- | ----------- | -------- |
|result| StackDiff | stack diff information | |
| err | Error | error code and message | `{"code":"invalidPath"， "message":"stack not exist"}` |

the StackDiff result should provide  at least  following information on the frontend abstraction level:
- the expected status of each component in the stack
- the actual runtime status of each component in the stack

**Comment by healthjyk** [comment]
This is a quite important part of service layer construction,  and seems belong to #248 
I have provide a realization of list templates, but there is some difference,  input field is fsPath -> path.
Hope it will satisfy your demand 😊 @amyXia1994

**Comment by amyXia1994** [comment]
please provide API for `kusion init` command to directly generate project without user-interactions:

now `kusion init` support `--custom-params`, `--yes` and `--force` options to skip prompt process to generate the project files. But there's one step that cannot be skipped: user must choose a template interactively, and cannot specify the target template to use from command line.

Here's the usage example for now:

➜ kusion init /Users/amy/work/open/kusion-templates/code-city/ --custom-params='{"ProjectConfig":{"AppName":"gocity","ContainerPort":4000,"ServicePort":4001},"ProjectName":"code-city","StacksConfig":{"dev":{"Image":"howieyuen/gocity:latest"}}}' --yes --force

? Please choose a template:  [Use arrows to move, type to filter]
> code-city    Code City metaphor for visualizing Go source code in 3D.

### What do I need

1. when there is only one template in the provided templated directory, skip the interactive selection process and use that single template directly.

2. provide an option to choose a template by name:

`kusion init https://github.com/KusionStack/kusion-templates.git --online=true --template=code-city`
