### ISSUE TITLE
When "kusion apply" with config change, expect terraform provider to update, but it triggers delete and create.  

### ISSUE THREAD

**Issue by ArronMingCN** [KusionStack/kusion#268]
When "kusion apply" with config change, expect terraform provider to update, but it triggers delete and create.  

## Bug Report

When "kusion apply" with config change, expect terraform provider to update, but it triggers delete and create. This case happens in multiple resources management scene with terraform provider.

### 1. Minimal reproduce step (Required)

When create multiple instances with the same resource, we redefine the name that appends on kusion id using instance number . For example:
"id": "testNamespace:testProvider:testProviderType:instance1",
"id": "testNamespace:testProvider:testProviderType:instance2",
"id": "testNamespace:testProvider:testProviderType:instance3",

1. update the kusion config (resource parameter) which belongs to one of the current instance let's say instance2.
2. trigger "kusion apply", kusion says update instance2 and show correct diff,which is expected. But when I check the terraform provider log, it triggers delete and create actually which is unexpected.
3. find the difference in the hidden terraform folder:
before update, the existed resource in terraform.tfstate shows:
"name" = "testNamespace:testProvider:testProviderType:instance2"
after the kusion update process(terraform delete and create), the file terraform.tfstate shows:
"name" = "instance2"

### 2. What did you expect to see? (Required)

With config pararmter change in multiple instance mangement scene, trigger kusion apply to upadte, the terraform trigger updatge too.

### 3. What did you see instead (Required)
With config pararmter change in multiple instance mangement scene, trigger kusion apply to upadte, the terraform trigger delete and create.

### 4. What is your KusionStack components version? (Required)
releaseVersion: v0.7.4-alipay.rc.2+15852eaf

**Comment by SparkYuan** [comment]
@ArronMingCN Thanks for your bug report. We have reproduced this bug, and it will be fixed recently.
