### ISSUE TITLE
Feat: support native kubernetes manifests in kusion

### ISSUE THREAD

**Issue by panshuai-ps** [KusionStack/kusion#278]
### What would you like to be added?

Kusion supports deploying native kubernetes manifests or referencing native kubernetes manifest files.

### Why is this needed?

 I have many native kubernetes manifests, and the cost of converting them to KCL language is too high for me.

**Comment by ldxdl** [comment]
Agree. Kusion should support raw kube manifests, helm charts, kustomize projs... in the first place. Variety is very important for users.

**Comment by SparkYuan** [comment]
@panshuai-ps Thanks for your proposal. We will think about it and update further actions here
