### ISSUE TITLE
Improve the user experience of kusion apply in the scenario of long processing time

### ISSUE THREAD

**Issue by liu-hm19** [KusionStack/kusion#294]
### What would you like to be added?

A progress bar which can display the elapsed time in real-time when execute the kusion apply command. 

### Why is this needed?

![image](https://user-images.githubusercontent.com/78610302/227863777-0e9fb5ed-a64a-4a92-8da4-dd5d39d0e517.png)

As shown in the figure, current progress bar can only display the total elapsed time and cannot show the time consumed of the apply process in real-time. When the deployment time is relatively long, users may be easily confused by whether the apply process has met an accident.

**Comment by howieyuen** [comment]
yes, truly is, the pterm project is optimizing process bar style, glad to see the new release.
