### ISSUE TITLE
Feat: Support compile output and live-preview at the abstraction level

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#329]
### Compile output at the abstraction level

`kusion compile` by default **display the stack's final spec at the abstraction level** and provides options for users to decide whether to display them at the backend level.

### Live Preview at the abstraction level

`kusion preview` and `kusion apply` by default display **the stack's live diff between the frontend spec and the actual runtime's frontend representation** and provides options for users to decide whether to display them at the backend level.

## Migration Strategy

For a smooth transition, the old default behavior(to display the output in the backend level) needs to be kept for a while and use a feature flag to switch to the frontend output.

## Background

As stated in [konfig and models concept](https://kusionstack.io/docs/reference/model/concept/), the Kusion Models aims to simplify the user interface to the infra resources: 
- the frontend models target end-users, are more user-friendly and user-readable, by abstracting necessary properties exposed to the user
- the backend models target underlying runtimes and should not be exposed to end users by default.

But now the `kusion compile` and `live-preview` features provide output at the raw Kubernetes resource level: the `stdout.golden.yaml`, the live diff result - resource summary and details.

**Comment by amyXia1994** [comment]
Here's an example to show the comparison between the frontend/backend spec of the [guestbook/dev](https://github.com/KusionStack/konfig/tree/main/appops/guestbook/dev) stack:

- frontend spec
![image](https://user-images.githubusercontent.com/29722609/233896942-2995f901-7f65-438f-9f49-9ad3f5ae5309.png)

- backend spec
![image](https://user-images.githubusercontent.com/29722609/233897035-e9cd1152-c086-4943-a8d1-a547f6934bf6.png)

**Comment by cytnju** [comment]
It looks great! Many times, developers pay more attention to the final result combined with main.k and base.k. The frontend spec is more human-friendly, and users who are not familiar with k8s can quickly understand what changes they have actually made.
By the way, it would be better if resource spec keep the same format with the backend spec.

**Comment by amyXia1994** [comment]
> 

Thanks for your feedback! 

> it would be better if resource spec keep the same format with the backend spec.

Good suggestion, I've noticed that, too. The `resource spec` uses a built-in type `unit.Unit` and the frontend output format needs to be optimized. cc @Peefy The ideal presentation of the frontend preview would be:

![preview](https://user-images.githubusercontent.com/29722609/233926941-604727ec-ea06-48c9-b7ce-1840f06ad24a.png)

**Comment by adohe** [comment]
Close as out of date.
