### ISSUE TITLE
Feat: kusion init support --target(-t) option to set the target path to output the generated files

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#344]
### What would you like to be added?

`kusion init` support --target(-t) option to set the target path to output the generated files
if not set, the files will be output to the current workdir, just as the current implementation.

### Why is this needed?

to generate the project to specified directory, maybe not current workdir

**Comment by skoenig** [comment]
@amyXia1994 Is the implementation of this option still wanted considering the recent refactorings?

**Comment by adohe** [comment]
@liu-hm19 could you please confirm this?

**Comment by liu-hm19** [comment]
@skoenig Hi, thanks for your interest in our project! In the upcoming **v0.11.0** release next week, we have simplified the usage of `kusion init` cmd. The option mentioned in this issue has not been implemented yet, but it is still necessary. We would greatly appreciate it if you would like to submit a pull request to contribute to the relevant feature : ) 

You can also join our slack ( https://kusionstack.slack.com/ ) for a more convenient communication.

**Comment by skoenig** [comment]
Thanks for the quick response @liu-hm19! I gave it a try with #954  
I'd like to join the Slack workspace but the [invite link on www.kusionstack.io](https://join.slack.com/t/kusionstack/shared_invite/zt-19lqcc3a9-_kTNwagaT5qwBE~my5Lnxg) does not work (anymore).

**Comment by SparkYuan** [comment]
> Thanks for the quick response @liu-hm19! I gave it a try with #954 let me know if I can improve something. I'd like to join the Slack workspace but the [invite link on www.kusionstack.io](https://join.slack.com/t/kusionstack/shared_invite/zt-19lqcc3a9-_kTNwagaT5qwBE~my5Lnxg) does not work (anymore).

Thanks for your response. We have updated the Slack invite link in the repo readme. You can join our Slack with the latest [link](https://join.slack.com/t/kusionstack/shared_invite/zt-2drafxksz-VzCZZwlraHP4xpPeh_g8lg). Feel free to contact me if you have any questions :)

**Comment by liu-hm19** [comment]
@skoenig Thanks for your participation! I'll review the code a.s.a.p. Your contribution will be appreciated in the release note after successfully merged : )

**Comment by liu-hm19** [comment]
@skoenig This issue has been closed and thanks a lot for your contribution! We will appreciate your contribution in the release note of upcoming **v0.11.0** version of Kusion. Please feel free to submit more issues/PRs and join the **KusionStack** community. We can nominate you as a member of the project in the future : )
