### ISSUE TITLE
kusion produces preview failed error in some cases

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusion#348]
### What happened?

```
kusion apply -w appops/guestbook/dev --ignore-fields="metadata.generation,metadata.managedFields"
❌  preview failed.
      Kind: ERROR, Code: INTERNAL, Message: apps/v1:Deployment:guestbook:redis-follower dependson v1:Service:guestbook:redis-leader, cannot delete resource v1:Service:guestbook:redis-leader
```

### What did you expect to happen?

show the stack resource change like following:
```
Stack: dev  ID                                           Action
* ├─     v1:Namespace:guestbook                       UnChange
* ├─     v1:Service:guestbook:redis-follower          UnChange
* ├─     v1:Service:guestbook:frontend                UnChange
* ├─     apps/v1:Deployment:guestbook:redis-leader    Delete
* ├─     apps/v1:Deployment:guestbook:redis-follower  UnChange
* ├─     apps/v1:Deployment:guestbook:frontend        Update
* └─     v1:Service:guestbook:redis-leader            Delete
```

### How can we reproduce it (as minimally and precisely as possible)?

in konfig/appops/guestbook/dev:

- modify the base/base.k: 
    - add `replicas = 4` configuration in the `guestbookFrontend` component
    - remove the code block of the `redisLeader` component
- run `kusion apply -w appops/guestbook/dev`

### Kusion version

<details>

```console
$ kusion version
releaseVersion: v0.8.0+4ccdceb2
gitInfo:
    latestTag: v0.8.0
    commit: 4ccdceb2f357749489a78aa27a6c5d3d05b996a3
    treeState: clean
buildInfo:
    goVersion: go1.19
    GOOS: darwin
    GOARCH: arm64
    numCPU: 10
    compiler: gc
    buildTime: "2023-05-15 17:47:32"
dependency:
    kclvmgoVersion: v0.4.7-0.20230509063441-affee8026160
    kclPluginVersion: v0.4.4
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by SparkYuan** [comment]
@amyXia1994 The error message here is as expected. `redisFollower` depends on `redisLeader` and we cannot delete a father node before deleting a child node.

**Comment by SparkYuan** [comment]
@amyXia1994 The error message here is as expected. `redisFollower` depends on `redisLeader` and we cannot delete a father node before deleting a child node.

**Comment by amyXia1994** [comment]
> @amyXia1994 The error message here is as expected. `redisFollower` depends on `redisLeader` and we cannot delete a father node before deleting a child node.

I got it. My instinct is that deleting one component should not depend on another, more precisely in this case, deleting the `redis-leader Deployment` should not depend on `redis-follower Service`. But I understand the dependency is set by design since users could not define dependency relations precisely.

I'll close the issue now.
