### ISSUE TITLE
User Experience: unify the experience of the kusion installation

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#355]
### What would you like to be added?

1, delete Dockerfile_kusionctl
2, delete *install kcl* in install.sh, cause kcl in embedded in kusion.

### Why is this needed?

When build kusion binary, kclvm is embedded. So, there is no need to install kclvm when install kusion.

**Comment by healthjyk** [comment]
When use *curl&sh* to install kusion. If adding "export PATH" in profile failed, the kusion still cannot work. Is there any way to handle this issue? I think there are two way:
1, first do add path, then mv binary from tmp dir to KUSION_HOME_DIR;
2, add some doc, if it's just a low-frequency issue.
And does this happen for homebrew&scoop&powershell?
What's your opinion? @SparkYuan @howieyuen

**Comment by healthjyk** [comment]
Besides, the uninstallation should take into consideration for *curl&sh*.

**Comment by healthjyk** [comment]
***HERE IS AN SUMMARY***
For the installation, it seems we have to do the following things to improve the experience:

**Comment by healthjyk** [comment]
***HERE IS AN SUMMARY***
For the installation, it seems we have to do the following things to improve the experience:
1, `support installing specified version`, in the way of homebrew and curl&bash. In the way of homebrew, multiple formulas should be added in [kusionstack/homebrew-tap](https://github.com/KusionStack/homebrew-tap), refer to [homebrew-core/ansible@2.8.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible%402.8.rb). And goreleaser.yml should be updated.
2, `provide better performance for linux`, support install kusion by yum and apt.
3, `provide unistallation`, in the way of curl&bash, should consider the handling of exporting env.
4, `deprecating unused elements`, delete  Dockerfile_kusionctl, kusionup is not a recommended way, kclvm is embedded in kusion, fix the wrong documents.
5, `fix the inconsistence`, especially the env.
6, `clear up scripts`, delete unused scripts in [kusion/scripts](https://github.com/KusionStack/kusion/tree/main/scripts), mv [install.sh](https://github.com/KusionStack/kusionstack.io/blob/main/static/scripts/install-kusion.sh) from repo ksuionstack.io to repo kusion.
...
Be Attention, this is for the installation of curl&bash and homebrew. For windows installation(scoop and powershell), should upgrade it later！

**Comment by healthjyk** [comment]
It seems that we should move kusion binary under /bin, which is the usual practice.

**Comment by howieyuen** [comment]
> It seems that we should move kusion binary under /bin, which is the usual practice.

let's do it

**Comment by SparkYuan** [comment]
@healthjyk Specifically, we should pay attention to the installation issues on the Windows platform.
