### ISSUE TITLE
kusion init --online failed

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#368]
### What happened?

When I use kusion init --online, an error “cloning templates repos: reference not found". Is it the problem of directory?
<img width="466" alt="image" src="https://github.com/KusionStack/kusion/assets/68334452/497f09de-02a3-4a50-b445-6e650935ebc3">

### What did you expect to happen?

Fix it

### How can we reproduce it (as minimally and precisely as possible)?

run kusion init --online

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>
v0.8.1

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by SparkYuan** [comment]
@healthjyk This issue can not be reproduced, please add more details about how to reproduce it.
