### ISSUE TITLE
Model: Update the auto-generated Kubernetes resources modules to latest stable version

### ISSUE THREAD

**Issue by ffforest** [KusionStack/kusion#384]
### What would you like to be added?

The [modules for Kubernetes resources](https://github.com/KusionStack/konfig/tree/main/base/pkg/kusion_kubernetes/api) are auto-generated by KCL auto-gen tool and are outdated.
These should be re-generated to include changes from the latest version of Kubernetes.

### Why is this needed?

To support mapping from KCL to newer versions of Kubernetes

### Acceptance Criteria

Kubernetes modules are re-generated with Kubernetes version 1.27.0+

**Comment by adohe** [comment]
not need anymore.
