### ISSUE TITLE
Documentation: Incorrect description on Chinese documentation

### ISSUE THREAD

**Issue by Mrcopytuo** [KusionStack/kusion#402]
### What happened?

On the [official Chinese document](https://kusionstack.io/zh-CN/docs/user_docs/getting-started/install/), the scoop command gives an error:
`scoop add bucket KusionStack https://github.com/KusionStack/scoop-bucket.git`

### What did you expect to happen?

It should be:
`scoop bucket add KusionStack https://github.com/KusionStack/scoop-bucket.git`
which is the same as the [English document](https://kusionstack.io/docs/user_docs/getting-started/install/)

### How can we reproduce it (as minimally and precisely as possible)?

Fix this error.

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by SparkYuan** [comment]
fixed
