### ISSUE TITLE
Toolchain: Decouple Kusion from model definition

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#403]
### What would you like to be added?

Kusion can take in any kcl file along with `stack.yaml` and `project.yaml` files without a local git repository that holds the model definitions (`Konfig` in the past, `Catalog` currently). ~structed in [Konfig struct](https://kusionstack.io/docs/user_docs/concepts/konfig#konfig-structure). We can prescribe the expected compile result as [Spec](https://github.com/KusionStack/kusion/blob/main/pkg/engine/models/spec.go)~

Kusion should leverage KCL package manager [kpm](https://github.com/kcl-lang/kpm) to manage the dependency on model definitions.

### Why is this needed?

Making Kusion more flexible and reducing the learning curve of using Kusion.

**Comment by Peefy** [comment]
I think I have a personal question that I need to add:

+ Can the `Spec` structure be closer to the Kubernetes object specification, so that Kusion can better integrate with downstream CD systems such as ArgoCD?

**Comment by SparkYuan** [comment]
> I think I have a personal question that I need to add:
> 
> * Can the `Spec` structure be closer to the Kubernetes object specification, so that Kusion can better integrate with downstream CD systems such as ArgoCD?

The [resource](https://github.com/KusionStack/kusion/blob/main/pkg/engine/models/spec.go#L5) in the Spec is k8s raw resource YAML combined with fields like`id`, `type` and`dependsOn` which are used by Kusion to manage resources. I will write an article to explain this in KusionStack website
