### ISSUE TITLE
User Experience: Kusion version with more accurate output

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#408]
### What would you like to be added?

When runnning kusion version:
- Delete "v" as the start of a version.
- Delete kclvm depedency.

![image](https://github.com/KusionStack/kusion/assets/68334452/f2d0e7cf-ddea-47c7-943b-f7abc3f3d757)

### Why is this needed?

The version should not start with "v", which is a tag not a version. For example, "0.8.1" is a version, while "v0.8.1" is a tag.
Kusion is not bound to kclvm, so there is no need of kclvm dependency.

**Comment by healthjyk** [comment]
From @liu-hm19, there always exists version-upgrade hint even if it's the latest version. 
Need to fix it!

**Comment by Wenfeng-GAO** [comment]
my `kusion version` output is as followed:
```bash
releaseVersion: v0.9.0+230d4cc3
gitInfo:
    latestTag: v0.9.0
    commit: 230d4cc37181e596942ce81a71452f84c47edfe0
    treeState: clean
buildInfo:
    goVersion: go1.21.3
    GOOS: darwin
    GOARCH: arm64
    numCPU: 8
    compiler: gc
    buildTime: "2023-10-16 21:55:42"
dependency:
    kclGoVersion: v0.6.0-alpha.1
    kclPluginVersion: v0.5.0
```
I have 2 questions:
1. I have `kclGoVersion` instead of `kclvmgoVersion`, does `kclGoVersion` need to be deleted either?
2. I didn't see any version-upgrade hint
