### ISSUE TITLE
kusion init failed, cannot choose template

### ISSUE THREAD

**Issue by study-renjie** [KusionStack/kusion#436]
### What happened?

![image](https://github.com/KusionStack/kusion/assets/43563096/e73d23c4-371b-48ea-8e7e-b05f016ce3eb)

### What did you expect to happen?

can choose template

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by SparkYuan** [comment]
You can use arrows to choose a template and press the `Enter` on your keyboard to continue. It will be helpful to provide your kusion version and OS version in your issue.

**Comment by SparkYuan** [comment]
@study-renjie I am closing this issue for now. Please reopen it if you have any further questions.
