### ISSUE TITLE
Remove mandatory validation of settings.yaml during kusion compile

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#440]
### What would you like to be added?

Remove the mandatory validation of `settings.yaml` during `kusion compile`
![20230807112852](https://github.com/KusionStack/kusion/assets/4793557/4e01aa35-3748-493a-ad07-ac09cad122fc)

### Why is this needed?

This file is not necessary during compilation. We can load contents in this file if it is provided but it should not be mandatory to validate it.

**Comment by ffforest** [comment]
Other subcommands may be using settings.yml as well, such as `kusion deps` or `kusion validate`
