### ISSUE TITLE
Use mock as the function name instead of monkey

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#445]
### What would you like to be added?

For the UT mock functions in pkg cmd/preview, use "mock" as the function name instead of "monkey", cause the UT repo monkey is not in use anymore.
Such as, change "monkeyPatchDetectProjectAndStack" to "mockPatchDetectProjectAndStack".

### Why is this needed?

The UT repo in use has changed.

**Comment by healthjyk** [comment]
The UT mock repo [bytedance/mockey](https://github.com/bytedance/mockey) is in use because of its support of MacOs M1, but there is almost no annotation and example at all. 
Is there any better choice, or we should develop it by ourselves.

**Comment by panshuai-ps** [comment]
> The UT mock repo [bytedance/mockey](https://github.com/bytedance/mockey) is in use because of its support of MacOs M1, but there is almost no annotation and example at all. Is there any better choice, or we should develop it by ourselves.

I don't think the name `monkeyPatchDetectProjectAndStack` needs to be changed, becase `monkey patch` is a term that refers to dynamically overloading or replacing functions, classes, methods, etc. to implement changes to existing code.
