### ISSUE TITLE
Go test donot support macos m1

### ISSUE THREAD

**Issue by chai2010** [KusionStack/kusion#48]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
macbook-m1:compile chai$ go env GOOS GOARCH
darwin
arm64
macbook-m1:compile chai$ go list
kusionstack.io/kusion/pkg/compile
macbook-m1:compile chai$ go test
# bou.ke/monkey
/Users/chai/go/pkg/mod/bou.ke/monkey@v1.0.2/replace.go:24:14: undefined: jmpToFunctionValue
FAIL    kusionstack.io/kusion/pkg/compile [build failed]
```

### 2. What did you expect to see? (Required)

Go test build successe

### 3. What did you see instead (Required)

```
# bou.ke/monkey
/Users/chai/go/pkg/mod/bou.ke/monkey@v1.0.2/replace.go:24:14: undefined: jmpToFunctionValue
FAIL    kusionstack.io/kusion/pkg/compile [build failed]
```

### 4. What is your KusionStack components version? (Required)

latest https://github.com/KusionStack/kusion/commit/2e9b7501fe3b2dd3a98468e374d0715c44cd70e2

**Comment by howieyuen** [comment]
how about golang/mock? 
v1.6.0 add ARM to support apple M1 chip
https://github.com/golang/mock/releases/tag/v1.6.0

**Comment by howieyuen** [comment]
https://github.com/agiledragon/gomonkey

**Comment by SparkYuan** [comment]
Replaced with github.com/bytedance/mockey
