### ISSUE TITLE
Three-way Diff and Merge for Kubernetes resources

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#51]
## Enhancement
Ref: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-apply-calculates-differences-and-merges-changes

**Comment by howieyuen** [comment]
## Background
Kubernetes support 4 types of PATCH type:
- `application/json-patch+json`: JSON Patch，as defined in [RFC6902](https://tools.ietf.org/html/rfc6902)
   A JSON patch is a sequence of operations that are executed on the resource;
   for example `{"op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ]}`.  
   To Kubernetes, this is a **patch** operation.
- `application/merge-patch+json`: JSON Merge Patch, as defined in [RFC7386](https://tools.ietf.org/html/rfc7386).
   A JSON Merge Patch is essentially a partial representation of the resource.
   The submitted JSON is combined with the current resource to create a new one, then the new one is saved.  
   To Kubernetes, this is a **patch** operation.
- `application/apply-patch+yaml`: Server Side Apply YAML (a Kubernetes-specific extension, based on YAML).
   All JSON documents are valid YAML, so you can also submit JSON using this media type. 
   See [Server Side Apply serialization](/docs/reference/using-api/server-side-apply/#serialization) for more details.  
   To Kubernetes, this is a **create** operation if the object does not exist, or a **patch** operation if the object already exists.
- `application/strategic-merge-patch+json`: JSON Merge Patch, as defined in [RFC7386](https://tools.ietf.org/html/rfc7386).
  A JSON Merge Patch is essentially a partial representation of the resource.
  The submitted JSON is combined with the current resource to create a new one, then the new one is saved.  
  To Kubernetes, this is a **patch** operation.

And `application/strategic-merge-patch+json` only supports built-in types, not available to CRs.

## Changes

**kusion apply** aims to support kinds of runtime. For kubernetes resources, we can try ** ServerSideApply** first, or else back to JSON Merge Patch which is available to k8s and non k8s resources. Manifests for 3-way merge come from **Modified**(user specified this time), **Original**(applied last time, stored in kusion_state.json) and **Current**(live state in runtime).

Q: How to judge SSA feature is on? this is stable in v1.22+
A: May be need to introduce a new flag to indicate "--server-side" is on or not.

### preview stage
we have a preview stage in **kusion apply** process, which can see the changed details differ with **Modified** and **Original**, now we can perform a 3-way diff among Modified/Original/Current。

## References
- https://github.com/kubernetes/website/pull/31261/files#r796815887
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by howieyuen** [comment]
### 3-Way-Diff

### Preview Stage: #91

- calculation of ChangeStep.Action
  1. calculate JSONMergePatch with `prior`, `plan` and `live` config
  2. apply with dry-run option and get `predictable` config
  3. compare `predictable` to `live`
- calculation of diff report
  1. directly use `predictable` and `live`

### Apply Stage: #90 
- refactor runtime interface, receive `dry-run` flag to get predictable result
