### ISSUE TITLE
contributing.md : not working

### ISSUE THREAD

**Issue by Madhurchandran** [KusionStack/kusion#514]
when I click on contributing guidline link it show nothing. 
![Screenshot 2023-09-06 064506](https://github.com/KusionStack/kusion/assets/100069538/3eb07c67-f0e8-41e5-a552-59a10ef91414)

**Comment by SparkYuan** [comment]
@Madhurchandran Thank you very much for your feedback. We are currently in the process of refactoring our project, and the new contribution guidelines will be updated within the next few days.

**Comment by Madhurchandran** [comment]
@SparkYuan can I create the documentation contributing.md file

**Comment by SparkYuan** [comment]
@Madhurchandran Sure, you are very welcome. Here is an architecture diagram that can help you better understand the entire project.
https://github.com/KusionStack/kusion/blob/main/docs/arch.png
