### ISSUE TITLE
code of conduct.md : is not available

### ISSUE THREAD

**Issue by Madhurchandran** [KusionStack/kusion#517]
why we need this 👍 
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions.

**Comment by Madhurchandran** [comment]
@SparkYuan assign me this issue can I try

**Comment by ffforest** [comment]
> @SparkYuan assign me this issue can I try

Hi @Madhurchandran feel free to take a crack at it. We recommend creating a fork of the repo and submit the PR for review.

**Comment by Madhurchandran** [comment]
@SparkYuan what is this CLA where to sign I made pull request I got rejected.

**Comment by SparkYuan** [comment]
@Madhurchandran You can sign the CLA by just posting a Pull Request Comment same as "I have read the CLA Document and I hereby sign the CLA"

**Comment by SparkYuan** [comment]
@Madhurchandran If you have any further questions, we can continue our discussion in your PR.

**Comment by Madhurchandran** [comment]
@SparkYuan again pull request fails

**Comment by Madhurchandran** [comment]
@SparkYuan my pull request got closed should I create new pull request.
