### ISSUE TITLE
Feature: Upgrade the AppConfig generator framework

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#529]
### What would you like to be added?

Current AppConfig generator framework implemented in `pkg/generator/appconfiguration/generator/app_configurations_generator.go`. 

We need a more extensible and readable framework that allows us to easily add a new generator.

### Why is this needed?

The current framework can generate the expected Spec model but contains some flaws:

1. Add one generator is trivial and we have to write some template codes to fulfill the framework
2. Some generator like`NewWorkloadGeneratorFunc` is not sustainable. Input params will continue growing when we add more features to the workload
3. etc

**Comment by Wenfeng-GAO** [comment]
I'd like to have a try, could you assign it to me, please ? @SparkYuan

**Comment by SparkYuan** [comment]
@Wenfeng-GAO Please write a design doc before you start coding. We will review your design before proceeding.

**Comment by Wenfeng-GAO** [comment]
> @Wenfeng-GAO Please write a design doc before you start coding. We will review your design before proceeding.

Sure. Where should I put the design doc ？To create a new pr or put it in this issue directly? @SparkYuan

**Comment by SparkYuan** [comment]
@Wenfeng-GAO Please create a new PR of the design doc and put it under the `docs` pkg.

**Comment by ffforest** [comment]
Completed with #573
