### ISSUE TITLE
Init menu does not have an EXIT option, only CTRL+C exit

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/kusion#53]
## Enhancement

The menu of `kusion init` does not have an EXIT option, only CTRL+C exit

screenshot:

![image](https://user-images.githubusercontent.com/9360247/170912569-d5465437-55eb-43fa-a1b6-307f1904d281.png)

**Comment by howieyuen** [comment]
I don't think we need an exit button here from a long time view. Now we have only have 2 templates on list, "exit" button can be touched quickly, but if we have 10+ templates, users have to move the arrow from top to the bottom, this will be a very annoying operation.
