### ISSUE TITLE
Kusion CLI & Engine 2022 roadmap discussion

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/kusion#56]
TODO

See our roadmap documents: 
* Kusion CLI: https://kusionstack.io/docs/governance/intro/roadmap/#kusion-cli-%E8%B7%AF%E7%BA%BF%E8%A7%84%E5%88%92
* Kusion Engine: https://kusionstack.io/docs/governance/intro/roadmap/#kusion-engine-%E8%B7%AF%E7%BA%BF%E8%A7%84%E5%88%92

**Comment by SparkYuan** [comment]
Ref: https://kusionstack.io/zh-CN/docs/governance/intro/roadmap/
