### ISSUE TITLE
Design: the boundary between App Dev and Platform Dev 

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#568]
### What would you like to be added?

Propose a design doc about the boundary between App Dev and Platform Dev and how to cooperate with each other.

### Why is this needed?

Some application configurations are quite clear, such as application developers being responsible for maintaining the application's images. However, when an application requires public internet access, who should be responsible for configuring and maintaining the LoadBalancer and DNS components involved?

In our daily work, we encounter many similar issues, with uncertainty about who should maintain specific application configurations and a lack of clarity regarding responsibilities among various teams. We should define a guiding practice of how to determine the responsibility between the two teams.

**Comment by adohe** [comment]
https://engineering.atspotify.com/2023/05/fleet-management-at-spotify-part-2-the-path-to-declarative-infrastructure/ -- The Spotify way provides some clues of how to enable collaboration between End-user and Infrastructure Developer.
