### ISSUE TITLE
Feat: Intent (Spec) versioning and storage

### ISSUE THREAD

**Issue by ffforest** [KusionStack/kusion#592]
### What would you like to be added?

Based on the [Kusion core workflow design](https://github.com/KusionStack/kusion/pull/579), the Intent(Spec) is now considered the Source Of Truth in the Kusion workflow and therefore needs to be versioned, stored and managed automatically by Kusion.

Also spec has been renamed to Intent as per our latest discussion.

### Why is this needed?

This reflects the changes discussed as part of the Kusion core workflow design.

**Comment by adohe** [comment]
Kusion v0.11.0 provides reduced Spec versioning and storage implementation.
