### ISSUE TITLE
Feat: use environment variable to specify the state backend

### ISSUE THREAD

**Issue by healthjyk** [KusionStack/kusion#595]
### What would you like to be added?

Use environment variable to specify the state backend, not the `--backend-type` and `--backend-config` of `kusion preview` and `kusion apply`.
 

### Why is this needed?

The state backend should be assigned to platform engineers, which have two ways to modify the configuration, the first is environment configuration, and the second is environment variables. Use the latter way, environment variables, to do the state backend configuration.

**Comment by ffforest** [comment]
Whether to put state backend into the environment config
