### ISSUE TITLE
Feat: design a more flexible generator framework to support adding customized generators

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#606]
### What would you like to be added?

Tasks:
-[ ] design a more flexible generator framework
-[ ] moving current generators to the catalog repo

### Why is this needed?

Current generators are hardcoded in the kusion repo which is not flexible to add customized generators. We need a more flexible framework. 
Can you provide more information about your requirements? @ddh-open

**Comment by ddh-open** [comment]
I customized some generators that extend k8s


schema code
`
import models.schema.v1.workload as wl
import models.schema.v1.trait as t
import models.schema.v1.accessories.database as db
import models.schema.v1.workload.secret as sec
import models.schema.v1.monitoring as m

## 原生k8s 扩展资源
import models.kubernetes.api.apps.v1 as appv1
import models.kubernetes.api.networking.v1 as ingressv1
import models.kubernetes.api.core.v1 as corev1

schema AppConfiguration:
    """ AppConfiguration is a developer-centric definition that describes how to run an Application.
    This application model builds upon a decade of experience at AntGroup running super large scale
    internal developer platform, combined with best-of-breed ideas and practices from the community.

    Attributes
    ----------
    workload: wl.Service | wl.Job, default is Undefined, required.
        Workload defines how to run your application code. Currently supported workload profile
        includes Service and Job.
    opsRule: t.OpsRule, default is Undefined, optional.
        OpsRule specifies collection of rules that will be checked for Day-2 operation.

    Examples
    --------
    # Instantiate an App with a long-running service and its image is "nginx:v1"

    import models.schema.v1 as ac
    import models.schema.v1.workload as wl
    import models.schema.v1.workload.container as c

    appConfiguration = ac.AppConfiguration {
        workload: wl.Service {
            containers: {
                "nginx": c.Container {
                    image: "nginx:v1"
                }
            }
        }
    }
    """

    # Workload defines how to run your application code.
    workload:                   wl.Service | wl.Job
    monitoring?:                m.Prometheus

    # OpsRule specifies collection of rules that will be checked for Day-2 operation.
    opsRule?:                   t.OpsRule

    # Database describes a locally deployed or a cloud provider managed database instance for the workload.
    database?:                  db.Database

    ###### Other metadata info
    # Labels and annotations can be used to attach arbitrary metadata as key-value pairs to resources.
    labels?:                    {str:str}
    annotations?:               {str:str}

    # Enhanced functions, you can customize k8s resources, and the same resources will be patched
    ingress?:                     {str: ingressv1.Ingress}

    deployments?:                 {str: appv1.Deployment}
    daemonSets?:                  {str: appv1.DaemonSet}
    statefulSets?:                {str: appv1.StatefulSet}

    secrets?:                     {str: corev1.Secret}
    persistentVolumeClaims?:      {str: corev1.PersistentVolumeClaim}
    configMaps?:                  {str: corev1.ConfigMap}
    services?:                    {str: corev1.Service}
`


generator code
`
package kubernetes

import (
	"dario.cat/mergo"
	"encoding/json"
	"fmt"
	yamlv2 "github.com/ghodss/yaml"
	"gopkg.in/yaml.v2"
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"kusionstack.io/kusion/pkg/generator/appconfiguration"
	"kusionstack.io/kusion/pkg/models"
	"kusionstack.io/kusion/pkg/projectstack"
)

// DeploymentGenerator is a struct for generating kubernetes resources.
type DeploymentGenerator struct {
	project     *projectstack.Project
	stack       *projectstack.Stack
	deployments map[string]map[string]interface{}
}

// NewDeploymentGenerator returns a new Kubernetes Generator instance.
func NewDeploymentGenerator(
	project *projectstack.Project,
	stack *projectstack.Stack,
	deployments map[string]map[string]interface{},
) (appconfiguration.Generator, error) {
	if len(project.Name) == 0 {
		return nil, fmt.Errorf("project name must not be empty")
	}

	return &DeploymentGenerator{
		project:     project,
		stack:       stack,
		deployments: deployments,
	}, nil
}

// NewDeploymentGeneratorFunc returns a new NewGeneratorFunc that returns a deployment instance.
func NewDeploymentGeneratorFunc(
	project *projectstack.Project,
	stack *projectstack.Stack,
	deployments map[string]map[string]interface{},
) appconfiguration.NewGeneratorFunc {
	return func() (appconfiguration.Generator, error) {
		return NewDeploymentGenerator(project, stack, deployments)
	}
}

// Generate generates kubernetes resource to the given spec.
func (g *DeploymentGenerator) Generate(spec *models.Spec) error {
	// Create an empty resource slice if it doesn't exist yet.
	if spec.Resources == nil {
		spec.Resources = make(models.Resources, 0)
	}

	for s, m := range g.deployments {
		name := appconfiguration.Camel2Case(s)
		objectMeta := metav1.ObjectMeta{
			Name:      name,
			Namespace: g.stack.Namespace,
		}
		typeMeta := metav1.TypeMeta{
			APIVersion: appsv1.SchemeGroupVersion.String(),
			Kind:       "Deployment",
		}
		// 转成k8s资源
		resource := appsv1.Deployment{
			TypeMeta:   typeMeta,
			ObjectMeta: objectMeta,
		}
		id := appconfiguration.KubernetesResourceID(typeMeta, objectMeta)
		notPatch := true
		for i, res := range spec.Resources {
			// 这样会被patch, 相同的key 会被覆盖
			if id == res.ID {
				notPatch = false
				// 装成json 对象
				yamlResource, err := yaml.Marshal(&m)
				if err != nil {
					return err
				}
				jsonResource, err := yamlv2.YAMLToJSON(yamlResource)
				err = json.Unmarshal(jsonResource, &resource)
				if err != nil {
					return err
				}
				unstructured, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&resource)
				if err != nil {
					return err
				}
				// 说明是一个资源， 则此时可以patch
				err = mergo.Merge(&(spec.Resources[i].Attributes), unstructured, mergo.WithSliceDeepCopy)
				if err != nil {
					return err
				}
			}
		}
		if notPatch {
			// 生成一个新的资源
			err := appconfiguration.AppendToSpec(models.Kubernetes, id, spec, &resource)
			if err != nil {
				return err
			}
		}
		notPatch = true
	}

	return nil
}

`

demo example
`
import catalog.models.schema.v1 as ac

### unityRestServer is the name of the deploy, here the camel case will be converted to "unity-rest-server"
unityRestServer: ac.AppConfiguration {
    workload.containers: {
        "unity-rest-server": {
                image = "ekb-repo.tencentcloudcr.com/ekb/unity:hotfix-Hotfix-20231118-20231118162230-3013313b"
                args: ["unity-release-rest-server"]
                env.ACCOUNT_V1BASEURL: "EMPTY"
                env.EKB_JAEGER_SAMPLER_TYPE: "const"
                readinessProbe.probeHandler.url: "http://localhost:1467/api/state/ready"
                readinessProbe.initialDelaySeconds: 30
                readinessProbe.failureThreshold: 3
                readinessProbe.periodSeconds: 10
                readinessProbe.successThreshold: 1
                readinessProbe.timeoutSeconds: 1
                resources.memory = "1Gi-3Gi"
        }
    }
    workload.replicas: 1
    workload.ports: [
        { port: 8080 }
    ]
		
    ### The patch here is compatible with various k8s configurations
    deployments: {
      ### This is the name of the deployment. If it already exists, it is the patch. If it does not exist, it is a new deploymentpatch.
      "unity-rest-server": {
        spec.template.spec.nodeName: "xxx"
        ### When patching a container, it is worth noting that patches are applied to array members. Currently, patches are distinguished based on index.
        spec.template.spec.containers: [{
            name: "unity-rest-server"
            imagePullPolicy: "Always"
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: "File"
            ### volume mount
            volumeMounts: [
              {
                name: "tz-config"
                mountPath: "/etc/localtime"
              }, 
              {
                name: "conf-unity"
                mountPath: "/conf"
              }
            ]
        }]
      }
    }
}
`

**Comment by ddh-open** [comment]
> ### What would you like to be added?
> Tasks: -[ ] design a more flexible generator framework -[ ] moving current generators to the catalog repo
> 
> ### Why is this needed?
> Current generators are hardcoded in the kusion repo which is not flexible to add customized generators. We need a more flexible framework. Can you provide more information about your requirements? @ddh-open

One of my requirements is to be compatible with k8s yaml native operations, and the other is that the generator needs to be decoupled from kusion.

**Comment by mouuii** [comment]
what does generate mean?

**Comment by SparkYuan** [comment]
> what does generator mean?
> 
> Is code below?
> 
> ```go
> // Generator represents a way to generate Intent. Usually, it is implemented by KCL, but we make it as an interface for a more general usage.
> // Anyone who implements this interface is regarded as a Generator, and can be integrated by the Kusion workflow.
> type Generator interface {
> 	GenerateSpec(o *Options, project *projectstack.Project, stack *projectstack.Stack) (*models.Intent, error)
> }
> ```

Yes, resource generators are located in this directory. `https://github.com/KusionStack/kusion/blob/main/pkg/generator/appconfiguration/generator/`

**Comment by SparkYuan** [comment]
> > ### What would you like to be added?
> > Tasks: -[ ] design a more flexible generator framework -[ ] moving current generators to the catalog repo
> > ### Why is this needed?
> > Current generators are hardcoded in the kusion repo which is not flexible to add customized generators. We need a more flexible framework. Can you provide more information about your requirements? @ddh-open
> 
> One of my requirements is to be compatible with k8s yaml native operations, and the other is that the generator needs to be decoupled from kusion.

Thank you for your feedback. We will discuss this in our team. Please feel free to comment on the issue if you have any further questions.

**Comment by ddh-open** [comment]
One thing is that we are cli. If we make a generator plug-in for cli, each user must install it when using it. At present, there is no way we can abstract the generator output and use a schema to describe it. Kusion needs the output according to the input configured by the schema, and the generator works according to the input configuration and the required output.
