### ISSUE TITLE
beta发布回滚能力

### ISSUE THREAD

**Issue by yihuan6** [KusionStack/kusion#630]
### What would you like to be added?

beta发布后，如果第一个容器出现异常，是否可以只回滚第一个容器

### Why is this needed?

目前beta发布，如果第一个容器出现问题，需要停止变更，重新发一次代码变更，影响较大

**Comment by ffforest** [comment]
Kusion to support rollback in beta releases. 
During a beta release, rollback the first pod if reports error.
