### ISSUE TITLE
kusion apply runtime error with little debug info

### ISSUE THREAD

**Issue by witcxc** [KusionStack/kusion#763]
### What would you like to be added?

![image](https://github.com/KusionStack/kusion/assets/5127780/b805d1a8-fd04-4078-b240-07fce918dcfa)

when trying to use a new tf provider to complete a job, something is wrong, nearly can't debug. Need to add some detail info about the failure.

### Why is this needed?

It will be efficient to view the error info in detail directly，can save a lot of time

**Comment by adohe** [comment]
@healthjyk ptal~

**Comment by healthjyk** [comment]
Thanks for your issue. Can you give more information? When does this bug happen? What's the specific bug?
